# config_extend.py
# Local overrides loaded after config.py (main.py: from config_extend import *).
# This config_api replaces the one in config.py, including the mdm and wisetech POC routes.

config_api = {
# index
"/": {"id": 35, "is_token": False},
"/health": {"id": 36, "is_token": False},
"/info": {"id": 17, "is_token": False, "cache": {"mode": "inmemory", "ttl_sec": 300, "is_per_user": False}},
"/openapi.json": {"id": 37, "is_token": False},
"/static": {"id": 77, "is_token": False},
"/pgweb": {"id": 99, "is_token": False},
"/websocket": {"id": 38, "is_token": False, "is_active": False},
# auth
"/auth/login-password": {"id": 91, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 10, "window_sec": 60}},
"/auth/signup-username-password": {"id": 39, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 5, "window_sec": 60}},
"/auth/login-username-password": {"id": 40, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 10, "window_sec": 60}},
"/auth/login-email-password": {"id": 41, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 10, "window_sec": 60}},
"/auth/login-mobile-password": {"id": 42, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 10, "window_sec": 60}},
"/auth/login-id-ext-password": {"id": 103, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 10, "window_sec": 60}},
"/auth/login-email-otp": {"id": 43, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 5, "window_sec": 60}},
"/auth/login-mobile-otp": {"id": 44, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 5, "window_sec": 60}},
"/auth/login-google": {"id": 45, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 10, "window_sec": 60}},
# my
"/my/profile": {"id": 46, "is_token": True},
"/my/ping": {"id": 92, "is_token": True},
"/my/token-refresh": {"id": 47, "is_token": True},
"/my/api-usage": {"id": 48, "is_token": True},
"/my/object-create": {"id": 49, "is_token": True},
"/my/object-read": {"id": 50, "is_token": True},
"/my/object-update": {"id": 51, "is_token": True},
"/my/object-delete": {"id": 52, "is_token": True},
"/my/object-delete-all": {"id": 53, "is_token": True},
"/my/message-inbox": {"id": 56, "is_token": True},
"/my/message-thread": {"id": 57, "is_token": True},
"/my/object-create-mongodb": {"id": 58, "is_token": True},
"/my/blob-preview-urls": {"id": 65, "is_token": True},
"/my/blob-delete-all": {"id": 59, "is_token": True},
"/my/blob-delete-url": {"id": 60, "is_token": True},
# private
"/private/send-email": {"id": 61, "is_token": True},
"/private/blob-upload-file": {"id": 62, "is_token": True},
"/private/blob-upload-presigned": {"id": 63, "is_token": True},
"/private/object-read": {"id": 102, "is_token": True},
"/private/users-list": {"id": 112, "is_token": True},
"/private/table-column-groupby": {"id": 107, "is_token": True, "cache": {"mode": "inmemory", "ttl_sec": 10, "is_per_user": False}},
"/private/table-column-distinct": {"id": 108, "is_token": True, "cache": {"mode": "inmemory", "ttl_sec": 10, "is_per_user": False}},
# public
"/public/object-create": {"id": 66, "is_token": False},
"/public/object-read": {"id": 14, "is_token": False, "cache": {"mode": "inmemory", "ttl_sec": 100, "is_per_user": False}},
"/public/converter-number": {"id": 67, "is_token": False},
"/public/otp-verify": {"id": 68, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 5, "window_sec": 60}},
"/public/otp-send-email": {"id": 69, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 3, "window_sec": 60}},
"/public/otp-send-mobile": {"id": 70, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 3, "window_sec": 60}},
"/public/otp-send-mobile-sns-template": {"id": 71, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 3, "window_sec": 60}},
"/public/table-column-groupby": {"id": 18, "is_token": False, "cache": {"mode": "inmemory", "ttl_sec": 10, "is_per_user": False}},
"/public/table-column-distinct": {"id": 105, "is_token": False, "cache": {"mode": "inmemory", "ttl_sec": 10, "is_per_user": False}},
"/public/blob-upload-file": {"id": 97, "is_active": False, "is_token": False},
"/public/blob-upload-presigned": {"id": 98, "is_active": False, "is_token": False},
"/public/password-hash": {"id": 100, "is_token": False, "rate_limit": {"mode": "inmemory", "limit": 5, "window_sec": 60}},
# admin
"/admin/sync": {"id": 1, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [1]}},
"/admin/object-create": {"id": 2, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/object-update": {"id": 3, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/object-read": {"id": 4, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/object-delete": {"id": 5, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [1]}, "user_check_deactivated": {"mode": "realtime"}, "user_check_deleted": {"mode": "realtime"}, "rate_limit": {"mode": "inmemory", "limit": 10, "window_sec": 60}},
"/admin/table-column-groupby": {"id": 104, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}, "cache": {"mode": "inmemory", "ttl_sec": 10, "is_per_user": False}},
"/admin/table-column-distinct": {"id": 106, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}, "cache": {"mode": "inmemory", "ttl_sec": 10, "is_per_user": False}},
"/admin/postgres-import": {"id": 8, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [1]}},
"/admin/redis-import": {"id": 9, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/mongodb-import": {"id": 11, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/blob-container-sas": {"id": 64, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [1]}},
"/admin/blob-preview-urls": {"id": 113, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [1]}},
"/admin/blob-container-read": {"id": 10, "is_token": True, "user_check_role": {"mode": "inmemory", "roles": [1]}},
"/admin/blob-container-ops": {"id": 12, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/blob-delete-url": {"id": 13, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/postgres-info": {"id": 84, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}, "cache": {"mode": "inmemory", "ttl_sec": 300, "is_per_user": False}},
"/admin/postgres-schema": {"id": 85, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}, "cache": {"mode": "inmemory", "ttl_sec": 300, "is_per_user": False}},
"/admin/postgres-query-runner-write": {"id": 6, "is_active": True, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [1]}},
"/admin/postgres-query-runner-read": {"id": 22, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/postgres-query-runner-read-export": {"id": 7, "is_token": True, "user_check_role": {"mode": "inmemory", "roles": [1]}},
"/admin/postgres-query-generator-ai": {"id": 90, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/mssql-query-runner-write": {"id": 21, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [1]}},
"/admin/mssql-query-runner-read": {"id": 23, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/mssql-query-runner-read-export": {"id": 89, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [1]}},
"/admin/clickhouse-query-runner-write": {"id": 93, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [1]}, "user_check_deactivated": {"mode": "realtime"}, "user_check_deleted": {"mode": "realtime"}},
"/admin/clickhouse-query-runner-read": {"id": 94, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
"/admin/clickhouse-query-runner-read-export": {"id": 95, "is_token": True, "user_check_role": {"mode": "inmemory", "roles": [1]}},
"/admin/clickhouse-query-generator-ai": {"id": 101, "is_token": True, "user_check_role": {"mode": "token", "roles": [1]}},
# mdm
"/mdm/read": {"id": 114, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [10]}},
"/mdm/review": {"id": 115, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [10]}},
"/mdm/export": {"id": 116, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [10]}},
# wisetech
"/wisetech/countries": {"id": 117, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [11]}, "user_check_deactivated": {"mode": "realtime"}, "user_check_deleted": {"mode": "realtime"}, "rate_limit": {"mode": "inmemory", "limit": 60, "window_sec": 60}},
"/wisetech/reference": {"id": 118, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [11]}, "user_check_deactivated": {"mode": "realtime"}, "user_check_deleted": {"mode": "realtime"}, "rate_limit": {"mode": "inmemory", "limit": 60, "window_sec": 60}},
"/wisetech/search": {"id": 119, "is_token": True, "user_check_role": {"mode": "realtime", "roles": [11]}, "user_check_deactivated": {"mode": "realtime"}, "user_check_deleted": {"mode": "realtime"}, "rate_limit": {"mode": "inmemory", "limit": 10, "window_sec": 60}},
}
