targetScope = 'resourceGroup'

@description('Region for all resources.')
param location string = 'southeastasia'

@description('Postgres admin password (secure, generated by deploy.sh).')
@secure()
param postgresAdminPassword string

@description('Token secret for JWT signing (secure, generated by deploy.sh).')
@secure()
param tokenSecret string

@description('Container image. First deploy uses placeholder; deploy.sh swaps to ACR image after first build.')
param containerImage string = 'mcr.microsoft.com/appsvc/staticsite:latest'

@description('Optional suffix to append to globally-unique names (acr, storage, kv) if a collision occurs.')
param uniqueSuffix string = ''

var prefix = 'mgh-atom-stg'
var aspName = 'asp-${prefix}'
var appName = 'app-${prefix}'
var uamiName = 'uami-${prefix}'
var pgName = 'pg-${prefix}'
var redisName = 'redis-${prefix}'
var lawName = 'log-${prefix}'
var appiName = 'appi-${prefix}'

var acrName = 'crmghatomstg${uniqueSuffix}'
var storageName = 'stmghatomstg${uniqueSuffix}'
var kvName = 'kv-mghatomstg${uniqueSuffix}'

var pgAdminLogin = 'atomadmin'
var pgDatabaseName = 'atom'

module identity 'modules/identity.bicep' = {
  name: 'identity'
  params: {
    location: location
    name: uamiName
  }
}

module observability 'modules/observability.bicep' = {
  name: 'observability'
  params: {
    location: location
    logAnalyticsName: lawName
    appInsightsName: appiName
  }
}

module acr 'modules/acr.bicep' = {
  name: 'acr'
  params: {
    location: location
    name: acrName
    uamiPrincipalId: identity.outputs.principalId
  }
}

module storage 'modules/storage.bicep' = {
  name: 'storage'
  params: {
    location: location
    name: storageName
  }
}

module postgres 'modules/postgres.bicep' = {
  name: 'postgres'
  params: {
    location: location
    name: pgName
    adminLogin: pgAdminLogin
    adminPassword: postgresAdminPassword
    databaseName: pgDatabaseName
  }
}

module redis 'modules/redis.bicep' = {
  name: 'redis'
  params: {
    location: location
    name: redisName
  }
}

module keyvault 'modules/keyvault.bicep' = {
  name: 'keyvault'
  params: {
    location: location
    name: kvName
    uamiPrincipalId: identity.outputs.principalId
    pgFqdn: postgres.outputs.fqdn
    pgAdminLogin: pgAdminLogin
    pgDatabaseName: pgDatabaseName
    postgresAdminPassword: postgresAdminPassword
    redisHostName: redis.outputs.hostName
    redisPort: redis.outputs.port
    redisPrimaryKey: redis.outputs.primaryKey
    tokenSecret: tokenSecret
  }
}

module app 'modules/app.bicep' = {
  name: 'app'
  params: {
    location: location
    aspName: aspName
    appName: appName
    uamiId: identity.outputs.id
    uamiClientId: identity.outputs.clientId
    containerImage: containerImage
    dockerRegistryUrl: 'https://${acr.outputs.loginServer}'
    appInsightsConnectionString: observability.outputs.appInsightsConnectionString
    appInsightsInstrumentationKey: observability.outputs.appInsightsInstrumentationKey
    logAnalyticsId: observability.outputs.workspaceId
    keyVaultUri: keyvault.outputs.uri
  }
}

output appName string = app.outputs.name
output appHostName string = app.outputs.defaultHostName
output acrName string = acr.outputs.name
output acrLoginServer string = acr.outputs.loginServer
output pgFqdn string = postgres.outputs.fqdn
output pgAdminLogin string = pgAdminLogin
output pgDatabaseName string = pgDatabaseName
output redisHostName string = redis.outputs.hostName
output redisPort int = redis.outputs.port
output keyVaultName string = keyvault.outputs.name
output keyVaultUri string = keyvault.outputs.uri
output uamiName string = identity.outputs.name
output uamiClientId string = identity.outputs.clientId
output uamiPrincipalId string = identity.outputs.principalId
output storageAccountName string = storage.outputs.name
output logAnalyticsName string = lawName
output appInsightsName string = appiName
